#!/usr/bin/env python3
import rclpy
from rclpy.node import Node
from sensor_msgs.msg import Image
from cv_bridge import CvBridge
import cv2
from ultralytics import YOLO
from vision_msgs.msg import Detection2D, Detection2DArray, ObjectHypothesisWithPose
import os

class DetectorNode(Node):
    def __init__(self):
        super().__init__('ed_detector_node')
        self.bridge = CvBridge()

        model_path = '/home/jetson/ultralytics/ultralytics/yolo11n.engine'
        self.model = YOLO(model_path, task='detect')
        self.get_logger().info(f'Loaded YOLO model from: {model_path}')

        self.publisher_ = self.create_publisher(Detection2DArray, '/detected_objects', 10)
        self.subscription = self.create_subscription(Image, '/camera/color/image_raw', self.image_callback, 10)

    def image_callback(self, msg):
        cv_image = self.bridge.imgmsg_to_cv2(msg, desired_encoding='bgr8')
        results = self.model(cv_image, verbose=False)

        detection_array_msg = Detection2DArray()
        detection_array_msg.header = msg.header

        for result in results:
            for box in result.boxes:
                detection = Detection2D()
                class_id = int(box.cls[0])
                class_name = self.model.names[class_id]
                score = float(box.conf[0])

                hypothesis = ObjectHypothesisWithPose()
                hypothesis.hypothesis.class_id = class_name
                hypothesis.hypothesis.score = score
                detection.results.append(hypothesis)

                bbox = box.xywh[0]
                detection.bbox.center.position.x = float(bbox[0])
                detection.bbox.center.position.y = float(bbox[1])
                detection.bbox.size_x = float(bbox[2])
                detection.bbox.size_y = float(bbox[3])

                detection_array_msg.detections.append(detection)

        if len(detection_array_msg.detections) > 0:
            self.publisher_.publish(detection_array_msg)

def main(args=None):
    rclpy.init(args=args)
    node = DetectorNode()
    rclpy.spin(node)
    node.destroy_node()
    rclpy.shutdown()

if __name__ == '__main__':
    main()